CREATE TABLE IF NOT EXISTS film (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100),
  description varchar(255),
  release_date date,
  duration integer,
  rating bigint
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255),
  login varchar(50),
  name varchar(100),
  birthday date
);

CREATE TABLE IF NOT EXISTS likes (
  user_id bigint,
  film_id bigint,
  PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship (
  user_id bigint,
  friend_id bigint,
  is_confirmed bool,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS genre (
  id bigint GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  name varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id bigint,
  genre_id bigint,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS rating (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50)
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    timestamp BIGINT NOT NULL,user_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    operation VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE likes ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE likes ADD FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE NO ACTION;

ALTER TABLE friendship ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE friendship ADD FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE NO ACTION;

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE NO ACTION;

ALTER TABLE film ADD FOREIGN KEY (rating) REFERENCES rating (id) ON DELETE CASCADE;